from setuptools import setup, find_packages


setup(name='eztranet',
      version='0.1',
      description='',
      long_description="""\
""",
      # Get strings from http://www.python.org/pypi?%3Aaction=list_classifiers
      classifiers=[],
      keywords='',
      author='',
      author_email='',
      url='',
      license='',
      package_dir={'': 'src'},
      packages=find_packages('src'),

      include_package_data=True,
      zip_safe=False,
      install_requires=['setuptools',
                        'zope.securitypolicy',
                        'zope.app.securitypolicy', # deprecated
                        'zope.component',
                        'zope.annotation',
                        'zope.browserresource',
                        'zope.app.dependable',
                        'zope.app.appsetup',
                        'zope.app.content',
                        'zope.publisher',
                        'zope.app.broken',
                        'zope.app.component',
                        'zope.app.generations',
                        'zope.app.error',
                        'zope.app.interface',
                        'zope.app.publisher',
                        'zope.app.security',
                        'zope.app.i18n',
                        'zope.app.locales',
                        'zope.app.zopeappgenerations',
                        'zope.app.principalannotation',
                        'zope.app.basicskin',
                        'zope.app.rotterdam',
                        'zope.app.folder',
                        'zope.app.wsgi',
                        'zope.i18n',
                        'zope.app.pagetemplate',
                        'zope.app.schema',
                        'zope.app.container',
                        'zope.app.debug',
                        'z3c.testsetup',
                        'zope.app.testing',
                        'zope.testbrowser',
                        'zope.login',
                        'zope.app.zcmlfiles',
                        'zope.file',
                        'zope.app.file',
                        'z3c.pagelet',
                        'z3c.layer.pagelet',
                        'z3c.menu.simple',
                        'zc.async[z3]',
                        'hachoir_parser',
                        'zope.index',
                        'zope.contenttype',
                        'zope.catalog',
                        'z3c.form',
                        'z3c.formui',
                        'z3c.contents',
                        'Pillow',
                        'zope.intid',
                        ],
      entry_points = """
      [paste.app_factory]
      main = eztranet.startup:application_factory

      [paste.global_paster_command]
      shell = eztranet.debug:Shell
      """,
      )
